import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter
from collections import defaultdict


# ── Required column layout ────────────────────────────────────────────────────
# A  = Title
# B  = URL
# C  = Thumbnail (image URL)
# D  = (blank spacer)
# E  = Item ID
# F  = (blank)
# G  = (blank)
# H  = Marketplace
# I  = (blank)
# J  = Seller Name
# K  = (blank)
# L  = (blank)
# M  = Brand
# N  = Price   ← extra, added at end of required cols

HEADERS = {
    "A": "Title",
    "B": "URL",
    "C": "Thumbnail",
    "D": "",
    "E": "Item ID",
    "F": "",
    "G": "",
    "H": "Marketplace",
    "I": "",
    "J": "Seller Name",
    "K": "",
    "L": "",
    "M": "Brand",
    "N": "Price",
    "O": "Item Location",
    "P": "Product Type",
}

HEADER_FILL  = PatternFill("solid", fgColor="2B2D42")
HEADER_FONT  = Font(bold=True, color="FFFFFF", name="Segoe UI", size=10)
ROW_FILL_A   = PatternFill("solid", fgColor="F8F8F2")
ROW_FILL_B   = PatternFill("solid", fgColor="EEEEEE")
BORDER_SIDE  = Side(style="thin", color="CCCCCC")
THIN_BORDER  = Border(bottom=BORDER_SIDE)

COL_WIDTHS = {
    "A": 55,   # Title
    "B": 50,   # URL
    "C": 45,   # Thumbnail
    "E": 16,   # Item ID
    "H": 14,   # Marketplace
    "J": 22,   # Seller
    "M": 18,   # Brand
    "N": 12,   # Price
    "O": 24,   # Item Location
    "P": 22,   # Product Type
}

MARKETPLACE = "ebay.com"


class ExcelExporter:
    def export(self, results: list[dict], filepath: str):
        """
        Export results to Excel.
        One tab per brand (grouped by item['brand']).
        Brands that belong to the same parent group share a tab if the user
        combined them (e.g. Toyota + Lexus both tagged 'Toyota').
        """
        wb = openpyxl.Workbook()
        wb.properties.creator = "Jerry Seidenstucker"
        wb.properties.title = "eBay Enforcement Harvester Report"
        wb.properties.description = "Generated by eBay Enforcement Harvester (Created by Jerry Seidenstucker)"
        wb.remove(wb.active)   # remove default sheet

        # group by brand
        by_brand = defaultdict(list)
        for item in results:
            by_brand[item.get("brand", "Unknown")].append(item)

        for brand, items in by_brand.items():
            ws = wb.create_sheet(title=self._safe_sheet_name(brand))
            self._write_sheet(ws, items, brand)

        wb.save(filepath)

    # ── sheet writer ──────────────────────────────────────────────────────────
    def _write_sheet(self, ws, items: list[dict], brand: str):
        # header row
        for col_letter, header_text in HEADERS.items():
            col_idx = openpyxl.utils.column_index_from_string(col_letter)
            cell = ws.cell(row=1, column=col_idx, value=header_text)
            cell.font  = HEADER_FONT
            cell.fill  = HEADER_FILL
            cell.alignment = Alignment(horizontal="center", vertical="center")

        ws.row_dimensions[1].height = 20

        # data rows (start at row 2)
        for row_num, item in enumerate(items, start=2):
            fill = ROW_FILL_A if row_num % 2 == 0 else ROW_FILL_B

            def cell(col_letter, value):
                idx  = openpyxl.utils.column_index_from_string(col_letter)
                c    = ws.cell(row=row_num, column=idx, value=value)
                c.fill = fill
                c.alignment = Alignment(vertical="center", wrap_text=False)
                c.border = THIN_BORDER
                return c

            title_cell = cell("A", item.get("title", ""))
            title_cell.font = Font(name="Segoe UI", size=9)

            url = item.get("url", "")
            url_cell = cell("B", url)
            if url:
                url_cell.hyperlink = url
                url_cell.font = Font(color="0563C1", underline="single",
                                     name="Segoe UI", size=9)
            else:
                url_cell.font = Font(name="Segoe UI", size=9)

            img_url = item.get("image_url", "")
            img_cell = cell("C", img_url)
            if img_url:
                img_cell.hyperlink = img_url
                img_cell.font = Font(color="0563C1", underline="single",
                                     name="Segoe UI", size=9)
            else:
                img_cell.font = Font(name="Segoe UI", size=9)

            cell("D", "")
            cell("E", item.get("item_id", "")).font = Font(name="Segoe UI", size=9)
            cell("F", "")
            cell("G", "")
            cell("H", item.get("marketplace", MARKETPLACE)).font = Font(name="Segoe UI", size=9)
            cell("I", "")
            cell("J", item.get("seller", "")).font = Font(name="Segoe UI", size=9)
            cell("K", "")
            cell("L", "")
            cell("M", brand).font = Font(name="Segoe UI", size=9)
            cell("N", item.get("price", "")).font = Font(name="Segoe UI", size=9)
            cell("O", item.get("location", "")).font = Font(name="Segoe UI", size=9)
            cell("P", item.get("product_type", "")).font = Font(name="Segoe UI", size=9)

        # column widths
        for col_letter, width in COL_WIDTHS.items():
            ws.column_dimensions[col_letter].width = width

        # freeze header row
        ws.freeze_panes = "A2"

        # auto-filter
        ws.auto_filter.ref = f"A1:P1"

    def _safe_sheet_name(self, name: str) -> str:
        """Excel sheet names max 31 chars, no special chars."""
        invalid = r'\/?*[]:'
        for ch in invalid:
            name = name.replace(ch, "_")
        return name[:31]

    def export_a2c2_dossier(self, registry_dict: dict, file_path: str):
        """Export an executive A2C2 / Brand Protection Master Store & Recidivism Dossier."""
        wb = openpyxl.Workbook()
        ws_summary = wb.active
        ws_summary.title = "A2C2 Store Recidivism"
        ws_summary.views.sheetView[0].showGridLines = True

        headers = [
            "Seller / Store Name",
            "Offense Status",
            "Infringing Brands",
            "Product Types",
            "Total Infringing Listings",
            "Total Market Value ($ USD)",
            "Known Locations",
            "First Detected",
            "Last Scanned",
            "Scan Count"
        ]

        ws_summary.append(headers)
        for col_num in range(1, len(headers) + 1):
            cell = ws_summary.cell(row=1, column=col_num)
            cell.fill = PatternFill("solid", fgColor="1E293B")
            cell.font = Font(bold=True, color="FFFFFF", name="Segoe UI", size=10)
            cell.alignment = Alignment(horizontal="center" if col_num in (2, 5, 6, 10) else "left", vertical="center")

        row_idx = 2
        for seller, data in sorted(registry_dict.items(), key=lambda x: x[1].get("total_value", 0.0), reverse=True):
            scans = data.get("scan_count", 1)
            status = "🚨 REPEAT OFFENDER" if scans > 1 or data.get("total_listings", 0) > 10 else "⚠️ FIRST STRIKE"
            brands = ", ".join(data.get("brands", []))
            pts = ", ".join(data.get("product_types", []))
            locs = ", ".join(data.get("locations", []))
            listings_count = data.get("total_listings", len(data.get("items", [])))
            total_val = f"${data.get('total_value', 0.0):,.2f}"

            row_data = [
                seller,
                status,
                brands,
                pts,
                listings_count,
                total_val,
                locs,
                data.get("first_seen", ""),
                data.get("last_scanned", ""),
                scans
            ]
            ws_summary.append(row_data)

            fill = ROW_FILL_A if row_idx % 2 == 0 else ROW_FILL_B
            for col_num in range(1, len(headers) + 1):
                c = ws_summary.cell(row=row_idx, column=col_num)
                c.fill = fill
                c.font = Font(name="Segoe UI", size=9, bold=(col_num == 2 and "REPEAT" in status))
                c.border = THIN_BORDER
                if col_num == 2 and "REPEAT" in status:
                    c.font = Font(name="Segoe UI", size=9, bold=True, color="B91C1C")
                if col_num in (2, 5, 6, 10):
                    c.alignment = Alignment(horizontal="center" if col_num in (2, 10) else "right")
            row_idx += 1

        summary_widths = [26, 22, 28, 26, 22, 24, 26, 20, 20, 12]
        for idx, w in enumerate(summary_widths, 1):
            ws_summary.column_dimensions[get_column_letter(idx)].width = w
        ws_summary.freeze_panes = "A2"
        ws_summary.auto_filter.ref = f"A1:{get_column_letter(len(headers))}1"

        all_items = []
        for seller, data in registry_dict.items():
            for it in data.get("items", []):
                all_items.append(it)

        if all_items:
            ws_items = wb.create_sheet(title="All Captured Listings")
            ws_items.views.sheetView[0].showGridLines = True
            item_headers = ["Seller", "Brand", "Product Type", "Item ID", "Title", "Price", "Location", "Listing URL", "Scanned At"]
            ws_items.append(item_headers)
            for col_num in range(1, len(item_headers) + 1):
                cell = ws_items.cell(row=1, column=col_num)
                cell.fill = PatternFill("solid", fgColor="334155")
                cell.font = Font(bold=True, color="FFFFFF", name="Segoe UI", size=10)

            for i_idx, it in enumerate(all_items, start=2):
                ws_items.append([
                    it.get("seller", ""),
                    it.get("brand", ""),
                    it.get("product_type", ""),
                    it.get("item_id", ""),
                    it.get("title", ""),
                    it.get("price", ""),
                    it.get("location", ""),
                    it.get("url", ""),
                    it.get("scanned_at", "")
                ])
                fill = ROW_FILL_A if i_idx % 2 == 0 else ROW_FILL_B
                for col_num in range(1, len(item_headers) + 1):
                    c = ws_items.cell(row=i_idx, column=col_num)
                    c.fill = fill
                    c.font = Font(name="Segoe UI", size=9)
                    c.border = THIN_BORDER

            item_widths = [20, 16, 20, 16, 50, 12, 22, 45, 18]
            for idx, w in enumerate(item_widths, 1):
                ws_items.column_dimensions[get_column_letter(idx)].width = w
            ws_items.freeze_panes = "A2"
            ws_items.auto_filter.ref = f"A1:{get_column_letter(len(item_headers))}1"

        wb.save(file_path)
